--- #YAML:1.0
name:               Catalyst-Plugin-Log4perl-Simple
version:            0.001
abstract:           Simple Log4perl setup for Catalyst application
author:
    - Peter Corlett <abuse@cabal.org.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
